mm: cma: Fix unused label warning
mm/cma.c:167:1: error: unused label 'err' [-Werror,-Wunused-label]
err:

Signed-off-by: celtare21 <celtare21@gmail.com>
Signed-off-by: Dusan Uveric <dusan.uveric9@gmail.com>